import './globals.css'
import type { Metadata } from 'next'

import AppHeader from '~/components/AppHeader/AppHeader';
import Footer from '~/components/Footer/Footer';
import WagmiProvider from '~/context/WagmiProvider';

export const metadata: Metadata = {
  title: 'Dutch Auction',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <link rel="icon" href="/wallets/metamask.svg" />
        <meta name="theme-color" content="#103145" />
        <link rel="apple-touch-icon" href="/apple-icon-57x57.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </head>
      <WagmiProvider>
        <body className="bg-v3-bg min-h-screen w-screen overflow-x-hidden flex flex-col justify-between">
          <AppHeader />
          <div className='flex-1'>
            {children}
          </div>
          <Footer />
        </body>
      </WagmiProvider>
    </html>
  )
}
